import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";

const Meticula = localFont({
  src: [
    { path: "./fonts/Meticula-Regular.ttf", weight: "400", style: "normal" },
    {
      path: "./fonts/Meticula-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Meticula.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
